name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    # runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      PORT: 50051
    steps:
      - uses: actions/checkout@v3
      - if: runner.os == 'Windows'
        run: rm 'C:\Windows\System32\bash.exe'
      - uses: dart-lang/setup-dart@v1.3
      - run: dart pub get
      - uses: actions/setup-node@v3
      - run: make proto
      # - run: curl https://i.jpillora.com/ktr0731/evans@v0.10.9! | bash
      - name: Run App
        run: |
          dart bin/plugin.dart & _PID=$! && sleep 10
          # echo '{ "implementation": "pact-rust","version":"1.2.3" }' | evans cli call InitPlugin --enrich
          kill $_PID
        shell: bash
      - run: make bin
      - run: |
          export PACT_PLUGIN_DIR=$GITHUB_WORKSPACE/../
          cd test/pact-js/plugins
          npm i
          npm run test:consumer
          npm run test:provider
